# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CircleSlider' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CircleSlider
  pod 'HGCircularSlider', '~> 2.2.1'
end
